In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Upload data

In [18]:
df=pd.read_csv("F:\\Project\\Student_Performance\\Data_Analysis\\data\\stud.csv")
df.head(3)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

Check NULL values

In [5]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

Check duplicates

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
for i in df.columns:
    print(f"column is {i} and its datatype:{df[i].dtype}")
    print(df[i].value_counts())
    print(f"**"*15)

column is gender and its datatype:object
gender
female    518
male      482
Name: count, dtype: int64
******************************
column is race_ethnicity and its datatype:object
race_ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64
******************************
column is parental_level_of_education and its datatype:object
parental_level_of_education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64
******************************
column is lunch and its datatype:object
lunch
standard        645
free/reduced    355
Name: count, dtype: int64
******************************
column is test_preparation_course and its datatype:object
test_preparation_course
none         642
completed    358
Name: count, dtype: int64
******************************
column is math_score and its datatype:int64
math_score
65    36
62    35
69    32
59    32
61    27
      ..
24     1
28     1
33     1
18     1
8      1
Name: count, Length: 81, dtype: int64
******************************
column is reading_score and its datatype:int64
reading_score
72    34
74    33
64    32
67    30
73    30
      ..
28     1
26     1
17     1
32     1
40     1
Name: count, Length: 72, dtype: int64
******************************
column is writing_score and its datatype:int64
writing_score
74    35
70    33
68    31
73    28
80    27
      ..
28     1
35     1
19     1
22     1
23     1
Name: count, Length: 77, dtype: int64
******************************

In [8]:
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [9]:
df.describe(include='all')

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
count,1000,1000,1000,1000,1000,1000.00000,1000.000000,1000.000000
unique,2,5,6,2,2,NaN,NaN,NaN
top,female,group C,some college,standard,none,NaN,NaN,NaN
freq,518,319,226,645,642,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,66.08900,69.169000,68.054000
std,NaN,NaN,NaN,NaN,NaN,15.16308,14.600192,15.195657
min,NaN,NaN,NaN,NaN,NaN,0.00000,17.000000,10.000000
25%,NaN,NaN,NaN,NaN,NaN,57.00000,59.000000,57.750000
50%,NaN,NaN,NaN,NaN,NaN,66.00000,70.000000,69.000000
75%,NaN,NaN,NaN,NaN,NaN,77.00000,79.000000,79.000000
max,NaN,NaN,NaN,NaN,NaN,100.00000,100.000000,100.000000

# Train Model

Sperate features and target column

In [40]:
x = df.drop(columns=['math_score'])
y = df[['math_score']]

Encoding

In [11]:
from sklearn.preprocessing import LabelEncoder

In [41]:
for i in x.columns:
    if x[i].dtype=='object':
        x = pd.get_dummies(x, columns=[i],drop_first=False,dtype=int)

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=42)

In [49]:
print(x_train.shape)
print(y_train.shape)

(700, 19)
(700, 1)

In [43]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train_scaled = sc.fit_transform(x)
x_test_scaled = sc.transform(x)

In [38]:
y_test=pd.DataFrame(y_test)

[29     62
 535    66
 695    79
 557    61
 836    73
        ..
 106    87
 270    69
 860    53
 435    50
 102    85
 Name: math_score, Length: 800, dtype: int64]

In [29]:
y_test=[y_test]

In [23]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [24]:
def evaluate_model(true,pred):
    mse=mean_squared_error(true,pred)
    mae=mean_absolute_error(true,pred)
    rmse=np.sqrt(mse)
    r2=r2_score(true,pred)

    return mse,mae,rmse,r2

In [47]:
print(x_train_scaled.shape)
print(y_train.shape)

(1000, 19)
(700, 1)

In [57]:
models= {
    'Linear Regression': LinearRegression(),
    'Redge Regression': Ridge(),
    'Lasso Regression': Lasso(),
    'KNN Regression': KNeighborsRegressor(),
    'Decission Tree Regression': DecisionTreeRegressor(),
    'Random Forest Regression': RandomForestRegressor(),
    'XGB Regression': XGBRegressor(),
    'AdaBoost Regression':AdaBoostRegressor()
}
model_ist=[]
r2_list=[]
for i in range(len(list(models))):
    model =list(models.values())[i]
    model.fit(x_train,y_train)

    #make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred =model.predict(x_test)

    #evaluation of the model

    mse,mae,rmse,r2=evaluate_model(y_test,y_test_pred)
    mse1,mae1,rmse1,r21= evaluate_model(y_train,y_train_pred)

    r2_list.append(r2)
    model_ist.append(list(models.keys())[i])

c:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [55]:
r2_list

[0.8758630443016737,
 0.8758146594128798,
 0.8167075654970513,
 0.7063319375968049,
 0.7329695999045414,
 0.8468141972301468,
 0.811029314994812,
 0.8445450228714328]

In [58]:
model_ist

['Linear Regression',
 'Redge Regression',
 'Lasso Regression',
 'KNN Regression',
 'Decission Tree Regression',
 'Random Forest Regression',
 'XGB Regression',
 'AdaBoost Regression']

In [60]:
model_select=pd.DataFrame([r2_list,model_ist])

In [61]:
model_select

,0,1,2,3,4,5,6,7
0,0.875863,0.875815,0.816708,0.706332,0.709913,0.847411,0.811029,0.833423
1,Linear Regression,Redge Regression,Lasso Regression,KNN Regression,Decission Tree Regression,Random Forest Regression,XGB Regression,AdaBoost Regression

In [ ]:
from slearn.linear_model import LinearRegre

In [65]:
import pickle

with open('model.pkl','wb') as file :
    pickle.dump(list(models.values())[1],file)